name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: sudo make check
      allow_failure: true
    - name: get logs
      run: cat ./test-suite.log
    - name: make distcheck
      run: make distcheck
